In [1]:
import numpy as np

In [2]:
array1 = np.array([0,1,2,3])
array1

array([0, 1, 2, 3])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.size

4

In [6]:
array1.shape

(4,)

In [8]:
array2_D = np.array([[0,1,2,3],[4,5,6,7]])
array2_D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
type(array2_D)

numpy.ndarray

In [10]:
array2_D.shape

(2, 4)

In [11]:
array2_D.size

8

In [13]:
list1 = [1,2,3,4,5]
np.array(list1,dtype =float)

array([1., 2., 3., 4., 5.])

In [14]:
array2_D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
np.zeros_like(array2_D)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
array1.ndim

1

In [17]:
array2_D.ndim

2

In [20]:
np.zeros((4,4),dtype =int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.ones_like(array2_D,dtype =float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [149]:
np.full((4,4),17)

array([[17, 17, 17, 17],
       [17, 17, 17, 17],
       [17, 17, 17, 17],
       [17, 17, 17, 17]])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
array1

array([0, 1, 2, 3])

In [27]:
np.tile(array1,3)

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])

In [150]:
np.repeat(array1,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [28]:
array2_D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
array2_D*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [30]:
array1

array([0, 1, 2, 3])

In [31]:
array2_D * array1

array([[ 0,  1,  4,  9],
       [ 0,  5, 12, 21]])

In [ ]:
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
array([0, 1, 2, 3]
      [0, 1, 2,3,])

In [32]:
np.diag((4,4))

array([[4, 0],
       [0, 4]])

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
array2_D + array1

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10]])

In [35]:
array2_D - array1

array([[0, 0, 0, 0],
       [4, 4, 4, 4]])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
np.arange(10).reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [44]:
np.arange(100).reshape(-1,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
np.arange(100).reshape(20,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [47]:
array1

array([0, 1, 2, 3])

In [48]:
array2 = np.array([6,7,8,9])

In [49]:
array2

array([6, 7, 8, 9])

In [52]:
np.concatenate((array1,array2),axis =0) #col wise concatenation

array([0, 1, 2, 3, 6, 7, 8, 9])

In [54]:
array1

array([0, 1, 2, 3])

In [55]:
array2

array([6, 7, 8, 9])

In [56]:
array2.T

array([6, 7, 8, 9])

In [57]:
array2_D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
array2_D.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [59]:
array_3 = np.transpose(array2_D)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [69]:
a = np.array([[1,2,3,5],[6,7,8,9],[5,6,7,8]])

In [71]:
a

array([[1, 2, 3, 5],
       [6, 7, 8, 9],
       [5, 6, 7, 8]])

In [73]:
np.transpose(a, axes =1)

ValueError: axes don't match array

In [74]:
array1

array([0, 1, 2, 3])

In [75]:
array2.T

array([6, 7, 8, 9])

In [80]:
np.concatenate((array1,array2.T))

array([0, 1, 2, 3, 6, 7, 8, 9])

In [81]:
array2_D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [82]:
array2_D_1 = array2_D.copy()

In [84]:
array2_D_1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [83]:
np.concatenate((array2_D,array2_D_1))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [86]:
array2_D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [85]:
array2_D_1.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [91]:
array2_D_1.T.shape

(4, 2)

In [87]:
b = np.concatenate((array2_D,array2_D_1))
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [92]:
b.shape

(4, 4)

In [90]:
np.concatenate((b,array2_D_1.T),axis =1)

array([[0, 1, 2, 3, 0, 4],
       [4, 5, 6, 7, 1, 5],
       [0, 1, 2, 3, 2, 6],
       [4, 5, 6, 7, 3, 7]])

In [93]:
array1

array([0, 1, 2, 3])

In [94]:
array2

array([6, 7, 8, 9])

In [96]:
tuples = (array1,array2)
np.vstack(tuples)

array([[0, 1, 2, 3],
       [6, 7, 8, 9]])

In [99]:
np.c_[array1,array2] 

array([[0, 6],
       [1, 7],
       [2, 8],
       [3, 9]])

In [104]:
array1.ndim

1

In [102]:
array1[:,None] #add new axis

array([[0],
       [1],
       [2],
       [3]])

In [109]:
np.column_stack((array1,array2))

array([[0, 6],
       [1, 7],
       [2, 8],
       [3, 9]])

In [ ]:
np.concatenate(axis), np.vstack,np.r_, np.column_stack,np.c_

In [112]:
array1

array([0, 1, 2, 3])

In [113]:
array2

array([6, 7, 8, 9])

In [114]:
array1 * array2

array([ 0,  7, 16, 27])

In [116]:
array1[:,None] 

array([[0],
       [1],
       [2],
       [3]])

In [117]:
array2

array([6, 7, 8, 9])

In [ ]:
array([[0,0,0,0]
       [1,1,1,1]
       [2,2,2,2]
       [3,3,3,3]])
[[6, 7, 8, 9]
[6, 7, 8, 9]
[6, 7, 8, 9]
[6, 7, 8, 9]]

In [115]:
array1[:,None] * array2

array([[ 0,  0,  0,  0],
       [ 6,  7,  8,  9],
       [12, 14, 16, 18],
       [18, 21, 24, 27]])

In [124]:
array2

array([6, 7, 8, 9])

In [134]:
array2[1]

7

In [125]:
array2[[0,3]]

array([6, 9])

In [126]:
array2_D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [137]:
array2_D[0,:]  #array_2d[rows,cols]

array([0, 1, 2, 3])

In [135]:
array2_D[0] #array2_D[0,:] 

array([0, 1, 2, 3])

In [136]:
array2_D[1]

array([4, 5, 6, 7])

In [130]:
array2_D[:,0]   #array_indexing[rows, cols]

array([0, 4])

In [131]:
array2_D[:,4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [132]:
array2_D[:,3]

array([3, 7])

In [133]:
array2_D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [141]:
array2_D[1][2]

6

In [144]:
array2_D[1, 2]

6

In [145]:
array2_D[0,3]

3

### If a dimension is given as __ in a reshaping operation, the other dimensions are automatically calculated.

A. Zero <br>
B. One<br>
C. Negative one<br>
D. Infinite

In [148]:
np.arange(100).reshape(10,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [155]:
c = np.arange(100).reshape(10,-1)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [156]:
c[::2] #-rows start:stop:step

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [157]:
c[::2,::2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [158]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [160]:
c.ndim

2

In [164]:
np.ravel(c)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [167]:
e = np.array(np.arange(100),ndmin=3) #3-D array

In [170]:
e

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
         48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
         64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
         80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
         96, 97, 98, 99]]])

In [168]:
e.ndim

3

In [171]:
array_new = np.ravel(e)
array_new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [173]:
b1,b2,b3,b4 = np.split(array_new,4)

In [174]:
b1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [175]:
b2

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [176]:
b3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74])

In [177]:
b4

array([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])

In [178]:
array1

array([0, 1, 2, 3])

In [179]:
np.split(array1,2)

[array([0, 1]), array([2, 3])]

In [180]:
np.split(array1,3)

ValueError: array split does not result in an equal division

In [181]:
array1

array([0, 1, 2, 3])

In [182]:
array2

array([6, 7, 8, 9])

In [183]:
np.dstack((array1,array2))

array([[[0, 6],
        [1, 7],
        [2, 8],
        [3, 9]]])

In [184]:
np.array([1,2,3,4,5],ndmin = 1)

array([1, 2, 3, 4, 5])

In [185]:
np.array([1,2,3,4,5],ndmin = 2)

array([[1, 2, 3, 4, 5]])

In [186]:
np.array([1,2,3,4,5],ndmin = 3)

array([[[1, 2, 3, 4, 5]]])

In [187]:
np.array([1,2,3,4,5],ndmin = 4)

array([[[[1, 2, 3, 4, 5]]]])